In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import yfinance as yf
import random
import plotly.express as px
import plotly.graph_objects as go

In [6]:
#Data cleaning and importing data from yFinance
tickers = ['F','AMD', 'BAC', 'ECL', 'GOOG', 'MSFT', 'NVO', 'QQQ', '^GSPC', 'WMT']
data = yf.download(tickers, period = '15y')
infodf = pd.DataFrame(data)
infodf.drop(infodf.columns[10:], axis = 1, inplace = True)
infodf.droplevel(level = 0, axis = 1)

[*********************100%***********************]  10 of 10 completed

Ticker,AMD,BAC,ECL,F,GOOG,MSFT,NVO,QQQ,WMT,^GSPC
Date,,,,,,,,,,
2010-12-27,8.050000,10.322868,42.454731,8.676879,14.891575,21.414635,8.235986,48.040276,13.097207,1257.540039
2010-12-28,8.090000,10.377323,42.581429,8.604872,14.806039,21.368860,8.331050,47.952549,13.138767,1258.510010
2010-12-29,8.080000,10.353989,42.513859,8.610021,14.857459,21.338343,8.302826,48.057808,13.221894,1259.780029
2010-12-30,8.140000,10.330647,42.640560,8.584302,14.804557,21.246798,8.325851,47.943802,13.219449,1257.880005
2010-12-31,8.180000,10.377323,42.589870,8.635734,14.683670,21.292574,8.360760,47.768349,13.185223,1257.640015
...,...,...,...,...,...,...,...,...,...,...
2025-12-18,201.059998,54.259998,262.920013,13.320000,303.750000,483.980011,47.610001,608.326233,114.830002,6774.759766
2025-12-19,213.429993,55.270000,263.589996,13.470000,308.609985,485.920013,48.090000,616.255981,114.360001,6834.500000
2025-12-22,214.949997,55.880001,267.380005,13.460000,311.329987,484.920013,48.099998,619.210022,112.599998,6878.490234
2025-12-23,214.899994,55.970001,264.739990,13.290000,315.679993,486.850006,51.610001,622.109985,110.900002,6909.790039
2025-12-24,215.039993,56.250000,265.579987,13.360000,315.670013,488.019989,52.560001,623.929993,111.610001,6932.049805

In [7]:
#Random Weight Generator
n = len(tickers)
def rweights(n):
    weights = []
    for i in range(n):
        weights.append(random.random())
    weights = weights / np.sum(weights)
    return weights

In [8]:
#Scale said dataframe from one
def scaler(df):
    scaled = (df / df.iloc[0]).droplevel(level = 0, axis = 1)
    return scaled
scaler(infodf)

Ticker,AMD,BAC,ECL,F,GOOG,MSFT,NVO,QQQ,WMT,^GSPC
Date,,,,,,,,,,
2010-12-27,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2010-12-28,1.004969,1.005275,1.002984,0.991701,0.994256,0.997862,1.011543,0.998174,1.003173,1.000771
2010-12-29,1.003727,1.003015,1.001393,0.992295,0.997709,0.996437,1.008116,1.000365,1.009520,1.001781
2010-12-30,1.011180,1.000754,1.004377,0.989331,0.994157,0.992163,1.010911,0.997992,1.009333,1.000270
2010-12-31,1.016149,1.005275,1.003183,0.995258,0.986039,0.994300,1.015150,0.994340,1.006720,1.000080
...,...,...,...,...,...,...,...,...,...,...
2025-12-18,24.976397,5.256291,6.192950,1.535114,20.397440,22.600433,5.780729,12.662838,8.767518,5.387311
2025-12-19,26.513042,5.354132,6.208731,1.552402,20.723798,22.691025,5.839010,12.827903,8.731633,5.434817
2025-12-22,26.701862,5.413224,6.298003,1.551249,20.906451,22.644328,5.840224,12.889394,8.597253,5.469798
2025-12-23,26.695651,5.421943,6.235818,1.531657,21.198563,22.734453,6.266402,12.949759,8.467454,5.494688
2025-12-24,26.713042,5.449067,6.255604,1.539724,21.197893,22.789088,6.381750,12.987644,8.521664,5.512389

In [9]:
#generate portfolio (random) asset allocation
investment = 10000
weights = rweights(n)
scaled_df = scaler(infodf)
portfolio = infodf.copy().droplevel(level = 0, axis = 1)
def asset_alloc(investment, weights, scaled_df, portfolio):
    
    for i, stock in enumerate(scaled_df):
        portfolio[stock] = weights[i] * scaled_df[stock] * investment
    portfolio['portfolio value'] = portfolio.sum(axis = 1, numeric_only = True)
    portfolio['daily change [%]'] = portfolio['portfolio value'].pct_change(1)*100
    portfolio['total % change'] = (portfolio['portfolio value']/portfolio['portfolio value'].iloc[0] - 1)*100
    return portfolio.fillna(0).round(2)

asset_alloc(investment, weights, scaled_df, portfolio)

Ticker,AMD,BAC,ECL,F,GOOG,MSFT,NVO,QQQ,WMT,^GSPC,portfolio value,daily change [%],total % change
Date,,,,,,,,,,,,,
2010-12-27,256.51,796.43,68.26,1654.40,1231.90,758.01,742.34,1489.40,1064.33,1938.41,10000.00,0.00,0.00
2010-12-28,257.79,800.63,68.46,1640.67,1224.83,756.39,750.91,1486.68,1067.71,1939.91,9993.98,-0.06,-0.06
2010-12-29,257.47,798.83,68.35,1641.65,1229.08,755.31,748.36,1489.94,1074.47,1941.87,10005.34,0.11,0.05
2010-12-30,259.38,797.03,68.56,1636.75,1224.71,752.07,750.44,1486.41,1074.27,1938.94,9988.54,-0.17,-0.11
2010-12-31,260.65,800.63,68.48,1646.55,1214.71,753.69,753.58,1480.97,1071.49,1938.57,9989.32,0.01,-0.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-18,6406.71,4186.25,422.72,2539.69,25127.70,17131.44,4291.25,18860.04,9331.57,10442.83,98740.22,1.12,887.40
2025-12-19,6800.88,4264.18,423.80,2568.29,25529.75,17200.11,4334.52,19105.89,9293.38,10534.92,100055.70,1.33,900.56
2025-12-22,6849.31,4311.24,429.89,2566.38,25754.76,17164.71,4335.42,19197.48,9150.36,10602.73,100362.27,0.31,903.62
2025-12-23,6847.72,4318.18,425.65,2533.97,26114.61,17233.03,4651.79,19287.38,9012.21,10650.97,101075.51,0.71,910.76
2025-12-24,6852.18,4339.79,427.00,2547.32,26113.79,17274.44,4737.42,19343.81,9069.90,10685.28,101390.92,0.31,913.91

In [10]:
#calculate portfolio statistics
def portfolio_stats(weights, investment):
    portfolio_df = asset_alloc(investment, weights, scaled_df, portfolio)
    daily_return_df = portfolio_df.drop(columns = ['daily change [%]', 'portfolio value', 'total % change']).pct_change(1).fillna(0)
    ERP = np.sum(weights*daily_return_df.mean())*252
    covariance = daily_return_df.cov()*252
    sd = np.sqrt(np.dot(weights.T, np.dot(covariance, weights)))
    rf = 0.0545
    sharpe = (ERP - rf)/sd
    return sharpe, ERP, sd
portfolio_stats(weights, investment)

(np.float64(0.6137667380774198),
 np.float64(0.16997013792293367),
 np.float64(0.18813358684870343))

In [11]:
#run monte carlo sim
simulations = 10000
weights_sim = np.zeros((simulations, n))
sharpe_sims = np.zeros(simulations)
ERP_sims = np.zeros(simulations)
sd_sims = np.zeros(simulations)
for i in range(simulations):
    weights = rweights(n)
    weights_sim[i,:] = weights
    sharpe_sims[i], ERP_sims[i], sd_sims[i] = portfolio_stats(weights, investment)

sharpe_sims.argmax()

np.int64(6828)

In [12]:
#create df out of sims:

results = pd.DataFrame({'vol': sd_sims.tolist(), 'sharpe': sharpe_sims.tolist(), 'ERP': ERP_sims.tolist()})
results

           vol    sharpe       ERP
0     0.197036  0.704269  0.193266
1     0.215667  0.690340  0.203384
2     0.196775  0.701632  0.192564
3     0.202498  0.720916  0.200484
4     0.196959  0.754235  0.203053
...        ...       ...       ...
9995  0.210507  0.649851  0.191298
9996  0.190627  0.680887  0.184296
9997  0.223094  0.635408  0.196256
9998  0.209035  0.684924  0.197673
9999  0.180716  0.678621  0.177138

[10000 rows x 3 columns]

In [15]:
fig = px.scatter(results, x = 'vol', y = 'ERP', color = 'sharpe', size = 'sharpe', hover_data = ['sharpe'] )
fig.add_trace(go.Scatter(x = [sd_sims[sharpe_sims.argmax()]], y = [ERP_sims[sharpe_sims.argmax()]], mode = 'markers', name = 'Optimal Point', marker = dict(size=[30], color = 'green')))
fig.update_layout({'plot_bgcolor': "white"})
fig.show()